config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'home/filter_period', 'home#filter_period'

  resources :tours, only: [:show]
  resource  :dashboard, only: [:show]
  resources :categories, only: [:index, :show]
  resources :budgets, only: [:new, :create, :show, :edit, :update]

  namespace :admin do
    resources :categories, only: [:index, :new, :create]
    resources :tours, only:[:index, :new, :create, :edit, :update, :destroy, :show]
    resources :high_seasons, only: [:index, :new, :create, :show]
    resources :prices, only: [:index, :new, :create, :show, :edit, :update]
    resources :transfers
  end
end

app/models/tour.rb
class Tour < ApplicationRecord

  validates :name, :description, :category, :attraction, :duration, :distance, :minimum_age, presence: true
  validates :minimum_age, inclusion: { in: 0..18, message: 'A Idade Mínima tem que estar entre 0 e 18'  }

  belongs_to :category

  has_many :prices
  has_many :transfers

end

app/controllers/admin/tours_controller.rb
module Admin
  class ToursController < ApplicationController
    layout 'admin_application'
    before_action :authenticate_user!

    def index
      @tours = Tour.all.order(:name)
    end

    def show
      @tour = Tour.find(params[:id])
    end

    def new
      @tour = Tour.new
    end

    def create
      @tour = Tour.new(tour_params)
      if @tour.save
        redirect_to([:admin, @tour])
      else
        flash[:error] = 'Passeio não pode ser cadastrado, verifique os dados'
        render :new
      end
    end

    def edit
      @tour = Tour.find(params[:id])
    end

    def update
      @tour = Tour.find(params[:id])
      if @tour.update(tour_params)
        redirect_to @tour
      else
        flash[:error] = 'Não foi possível atualizar o passeio'
        render :edit
      end
    end

    private
    def tour_params
      params.require(:tour).permit(:name, :description, :category_id,
                                   :attraction, :duration, :adult_price,
                                   :child_price, :baby_price, :distance, :site,
                                   :minimum_age)
    end
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def show
    @tour = Tour.find(params[:id])
    @prices = @tour.prices.where("end_date >= ?",Date.today).order("start_date ASC")
  end
end

app/views/admin/tours/_form.html.erb
<% unless flash.empty? %>
  <div class="alert alert-warning" role="alert"><%= flash[:error] %></div>
<% end %>
<%= simple_form_for([:admin, @tour]) do |f| %>
  <%= f.input :name, label: 'Nome' %>
  <%= f.input :description, label: 'Descrição' %>
  <%= f.association :category, label: 'Categoria' %>
  <%= f.input :attraction, label: 'Atrativo' %>
  <%= f.input :minimum_age, collection: 0..18, prompt: "Selecione a Idade Mínima", selected: 0, label: 'Idade Miníma'%>
  <%= f.input :duration, label: 'Duração' %>
  <%= f.input :distance, label: 'Distância' %>
  <%= f.input :site, label: 'Site' %>
  <%= f.submit txt_submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/tours/edit.html.erb
<%= render partial: 'form', locals: {txt_submit: 'Salvar'} %>

app/views/admin/tours/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
      <div class="row">
        <div class="col-sm-12">
          <table width="100%" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="tours-table" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
            <thead>
              <tr role="row">
                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column descending" style="width: 35%%;" aria-sort="ascending">Nome</th>
                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 30%%;">Atrativo</th>
                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 25%;">Categoria</th>
                <th class="text-center" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 10%%;">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @tours.each do |tour| %>
                <tr class="gradeA odd" role="row">
                  <td> <%= tour.name %> </td>
                  <td> <%= tour.attraction %> </td>
                  <td> <%= tour.category.name %> </td>
                  <td class="text-center">
                    <%= link_to edit_admin_tour_path(tour) do %>
                      <i class="fa fa-edit fa-fw"></i>
                    <% end %>                    
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- /.table-responsive -->
  </div>
  <!-- /.panel-body -->
</div>

app/views/admin/tours/new.html.erb
<%= render partial: 'form', locals: {txt_submit: 'Salvar Passeio'}%>

app/views/admin/tours/show.html.erb
<h1><%= @tour.name %></h1>
<br/>
<br/>
<div class="row">
  <div class="col col-lg-3">
    <strong>Categoria:</strong>
    <br/>
    <%= @tour.category.name %>
  </div>
  <div class="col col-lg-3">
    <strong>Atrativo:</strong>
    <br/>
    <%= @tour.attraction %>
  </div>
  <div class="col col-lg-3">
    <strong>Idade Mínima:</strong>
    <br/>
    <%= @tour.minimum_age %> anos
  </div>
  <div class="col col-lg-3">
    <strong>Duração:</strong>
    <br/>
    <%= @tour.duration %> minutos
  </div>
  <div class="col col-lg-3">
    <strong>Distância:</strong>
    <br/>
    <%= @tour.distance %> km
  </div>
</div>
<br/>
<div class="row">
  <div class="col col-lg-3">
    <strong>Site:</strong>
    <br/>
    <%= @tour.site %>
  </div>
</div>
<br/>
<div class="row">
  <div class="col col-lg-12">
    <strong>Descrição:</strong><br/>
    <%= @tour.description %><br/>
  </div>
</div>
<br/>
<br/>
<a href="javascript:history.back()" class="btn btn-default" role="button">Voltar</a>