config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'home/filter_period', 'home#filter_period'

  resources :tours, only: [:show]
  resource  :dashboard, only: [:show]
  resources :categories, only: [:index, :show]
  resources :budgets, only: [:new, :create, :show, :edit, :update]

  namespace :admin do
    resources :categories, only: [:index, :new, :create]
    resources :tours, only:[:index, :new, :create, :edit, :update, :destroy, :show]
    resources :high_seasons, only: [:index, :new, :create, :show]
    resources :prices, only: [:index, :new, :create, :show, :edit, :update]
    resources :transfers
  end
end

app/views/layouts/admin/_footer.html.erb
<footer class="container">
</footer>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Soma Bonita", dashboard_path, class: "navbar-brand" %>
    <%= link_to "Página Principal", root_path, class: "navbar-brand" %>
  </div>
  <!-- /.navbar-header -->

  <ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <!-- <li><a href="#"><i class="fa fa-user fa-fw"></i> Meu Perfil</a>
        </li>
        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Configurações</a>
        </li>
        <li class="divider"></li> -->
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out fa-fw"></i> Sair
          <% end %>
        </li>
      </ul>
      <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li>
          <%= link_to dashboard_path do %>
            <i class="fa fa-dashboard fa-fw"></i>Dashboard
          <% end %>
        </li>
        <li>
          <a href=""><i class="fa fa-plane fa-fw"></i> Passeios<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li> <%= link_to 'Listar Passeios', admin_tours_path %> </li>
            <li> <%= link_to 'Novo Passeio', new_admin_tour_path %> </li>
          </ul>
          <!-- /.nav-second-level -->
        </li>

        <li>
          <a href="#"><i class="fa fa-list fa-fw"></i> Categorias<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li> <%= link_to 'Listar Categorias', admin_categories_path %> </li>
            <li> <%= link_to 'Nova Categoria', new_admin_category_path %> </li>
          </ul>
          <!-- /.nav-second-level -->
        </li>

        <li>
          <a href="#"><i class="fa fa-list fa-fw"></i> Alta Temporada<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li> <%= link_to 'Listar Temporadas', admin_high_seasons_path %> </li>
            <li> <%= link_to 'Nova Temporada', new_admin_high_season_path %> </li>
          </ul>
          <!-- /.nav-second-level -->
        </li>

        <li>
          <a href="#"><i class="fa fa-list fa-fw"></i> Preços<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li> <%= link_to 'Listar Preços', admin_prices_path %> </li>
            <li> <%= link_to 'Novo Preço', new_admin_price_path %> </li>
          </ul>
          <!-- /.nav-second-level -->
        </li>
        <li>
          <a href="#"><i class="fa fa-list fa-fw"></i> Transportes<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li> <%= link_to 'Listar Transportes', admin_transfers_path %> </li>
            <li> <%= link_to 'Novo Transporte', new_admin_transfer_path %> </li>
          </ul>
          <!-- /.nav-second-level -->
        </li>
      </ul>
    </div>
  </nav>