config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'home/filter_period', 'home#filter_period'

  resources :tours, only: [:show]
  resource  :dashboard, only: [:show]
  resources :categories, only: [:index, :show]
  resources :budgets, only: [:new, :create, :show, :edit, :update]

  namespace :admin do
    resources :categories, only: [:index, :new, :create]
    resources :tours, only:[:index, :new, :create, :edit, :update, :destroy, :show]
    resources :high_seasons, only: [:index, :new, :create, :show]
    resources :prices, only: [:index, :new, :create, :show, :edit, :update]
    resources :transfers
  end
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :tour

  enum seat_type: {particular: 0, shared: 1}

  validates :name, presence: true
end

app/controllers/admin/transfers_controller.rb
class Admin::TransfersController < Admin::BaseController

  before_action :set_transfer, only: [:edit, :update, :destroy]

  def index
    @transfers = Transfer.all.map{|transfer| TransferPresenter.new(transfer)}
    flash[:notice] = 'Nenhum Transporte Cadastrado' unless @transfers.present?
  end

  def new
    @transfer = Transfer.new
    @seat_types = seat_types
  end

  def create
    @transfer = Transfer.new(transfer_params)
    if @transfer.save
      redirect_to ([:admin, @transfer])
    else
      flash[:error] = "Não foi possível criar transporte."
      @seat_types = seat_types
      render :new
    end
  end

  def edit
    @seat_types = seat_types
  end

  def update
    if @transfer.update(transfer_params)
      redirect_to ([:admin, @transfer])
    else
      @seat_types = seat_types
      flash[:error] = 'Não foi possível atualizar o transporte'
      render :edit
    end
  end

  def show
    @transfer = TransferPresenter.new(Transfer.find(params[:id]))
  end

  def destroy
    @transfer.destroy
    redirect_to admin_transfers_url
  end

  private

  def transfer_params
    params.require(:transfer).permit(:name, :tour_id, :seat_type)
  end

  def set_transfer
    @transfer = Transfer.find(params[:id])
  end

  def seat_types
    Transfer.seat_types.map do |key, _|
      [Transfer.human_attribute_name(key.to_sym), key]
    end
  end
end

app/views/admin/transfers/_form.html.erb
<% unless flash.empty? %>
  <div class="alert alert-warning" role="alert"><%= flash[:error] %></div>
<% end %>
<%= simple_form_for ([:admin, @transfer]) do |f| %>
  <%= f.input :name %>
  <%= f.association :tour %>
  <%= f.input :seat_type, as: :radio_buttons, collection: @seat_types %>
  <%= f.submit txt_submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/transfers/edit.html.erb
<%= render partial: 'form', locals: {txt_submit: 'Atualizar Transporte'} %>

app/views/admin/transfers/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
      <div class="row">
        <div class="col-sm-12">
          <table width="100%" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="transfers-table" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
            <thead>
              <tr role="row">
                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column descending" style="width: 35%%;" aria-sort="ascending">Nome</th>
                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 30%%;">Passeio</th>
                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 25%;">Tipo</th>
                <th class="text-center" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 10%%;">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @transfers.each do |transfer| %>
                <tr class="gradeA odd" role="row">
                  <td> <%= transfer.name %> </td>
                  <td> <%= transfer.tour.name %> </td>
                  <td> <%= transfer.seat_type %> </td>
                  <td class="text-center">
                    <%= link_to edit_admin_transfer_path(transfer) do %>
                      <i class="fa fa-edit fa-fw"></i>
                    <% end %>
                    <%= link_to admin_transfer_path(transfer), method: :delete, data: {confirm: 'Deseja deletar esse transporte?'} do %>
                      <i class="fa fa-close fa-fw"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              <% unless @transfers %>
                <span><%= flash[:notice] %></span>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- /.table-responsive -->
  </div>
  <!-- /.panel-body -->
</div>

app/views/admin/transfers/new.html.erb
<%= render partial: 'form', locals: {txt_submit: 'Criar Transporte'} %>

app/views/admin/transfers/show.html.erb
<h1><%= @transfer.name %></h1>
<br/>
<br/>
<div class="row">
  <div class="col col-lg-3">
    <strong>Tipo:</strong>
    <br/>
    <%= @transfer.seat_type %>
  </div>
  <div class="col col-lg-3">
    <strong>Passeio:</strong>
    <br/>
    <%= @transfer.tour.name %>
  </div>
  
<br/>
<br/>
<a href="javascript:history.back()" class="btn btn-default" role="button">Voltar</a>